- name: "Getting ODF workers from {{ zone_1 }}"
  shell: |
    oc get nodes -l topology.kubernetes.io/zone={{ zone_1 }} -o jsonpath='{range .items[*]}{@.metadata.name}{"\n"}'
  register: ocs_workers

- name: "I will create {{ partitions_total }} partitions per free DISK on servers in {{ zone_1 }}"
  shell: |
    oc debug node/{{ item }} -- lsblk -o NAME | grep ^[a-z] | while read disk
    do
        oc debug node/{{ item }} -- sfdisk --part-type /dev/$disk 1 &> /dev/null
        if [ "$?" -gt 0 ]
        then
                oc debug node/{{ item }} -- parted /dev/$disk -s mklabel gpt mkpart primary 1 25% mkpart primary 25% 50% mkpart primary 50% 75% mkpart primary 75% 100%
                oc debug node/{{ item }} -- partprobe /dev/$disk
                echo "/dev/$disk PARTITIONED:"
                oc debug node/{{ item }} -- parted /dev/$disk -s p
        else
                echo "/dev/$disk SKIPPED"
        fi
    done
  loop: "{{ ocs_workers.stdout_lines }}"

- name: "Partition on {{ zone_1 }} nodes"
  shell: |
         oc debug node/{{ item }} -- lsblk
  loop: "{{ ocs_workers.stdout_lines }}"
  register: osd_partition_results

- debug:
    msg: "{{ item.stdout_lines }}"
  loop: "{{ osd_partition_results.results }}"

- name: "Getting ODF workers from {{ zone_2 }}"
  shell: |
    oc get nodes -l topology.kubernetes.io/zone={{ zone_2 }} -o jsonpath='{range .items[*]}{@.metadata.name}{"\n"}'
  register: ocs_workers

- name: "I will create {{ partitions_total }} partitions per free DISK on servers in {{ zone_2 }}"
  shell: |
    oc debug node/{{ item }} -- lsblk -o NAME | grep ^[a-z] | while read disk
    do
        oc debug node/{{ item }} -- sfdisk --part-type /dev/$disk 1 &> /dev/null
        if [ "$?" -gt 0 ]
        then
                oc debug node/{{ item }} -- parted /dev/$disk -s mklabel gpt mkpart primary 1 25% mkpart primary 25% 50% mkpart primary 50% 75% mkpart primary 75% 100%
                oc debug node/{{ item }} -- partprobe /dev/$disk
                echo "/dev/$disk PARTITIONED:"
                oc debug node/{{ item }} -- parted /dev/$disk -s p
        else
                echo "/dev/$disk SKIPPED"
        fi
    done
  loop: "{{ ocs_workers.stdout_lines }}"

- name: "Partition on zone {{ zone_2 }} nodes"
  shell: |
         oc debug node/{{ item }} -- lsblk
  loop: "{{ ocs_workers.stdout_lines }}"
  register: osd_partition_results

- debug:
    msg: "{{ item.stdout_lines }}"
  loop: "{{ osd_partition_results.results }}"